### ISSUE TITLE
Dependent container using raw connection

### ISSUE THREAD

**Issue by ianstalk** [polkaned/dockerfiles#43]
My internet went out a few days ago, and I noticed that my actual IP address was showing up in a torrent's peer list after it came back. When I attached to the container and ran `expressvpn status` I got this:

```
# expressvpn status
A new version is available, download it from https://www.vlycgtx.com/latest#linux.

Unable to connect.

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'
```

Here's my `docker-compose.yml`:

```
version: "2.1"
services:
  expressvpn:
    container_name: transmission-expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE=${ACTIVATION_CODE}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      - 9091:9091

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=131
      - PGID=1002
      - TZ=America\New_York
    volumes:
      - /etc/docker-services/transmission:/config
      - /var/transmission/downloads:/downloads
    network_mode: service:expressvpn
    restart: unless-stopped
    depends_on:
      - expressvpn
```

Restarting the container fixed the issue, but I honestly would prefer that Transmission stopped working than have it using my raw IP address.
