### ISSUE TITLE
struggling with client container

### ISSUE THREAD

**Issue by pmbsa** [polkaned/dockerfiles#46]
Hi, I am hoping you might be able to offer a bit of guidance. I am using your expressvpn image, its all connecting out ok and the expressvpn status command says its all connected. 
My client container though is not behaving. I am accessing stuff that is geoblocked in the UK. My client container starts up and accessible via the [prts exposed by the expressvpn container BUT when it access's the geoblocked content its as if its not connecting through the vpn container.

my compose for the client service is this
``` 
spiplayer:
    env_file: .env
    volumes:
        - /nfs/spiplayer/cache:/root/.get_iplayer
        - /nfs/spiplayer/tv:/data/tv
        - /nfs/spiplayer/radio:/data/radio
        - /sys/fs/cgroup:/sys/fs/cgroup
    image: spiplayer:latest
    container_name: spiplayer
    restart: "unless-stopped"
    depends_on:
     - expressvpn
    network_mode: service:expressvpn
    build:
      context: spiplayer
      args:
        - releaseversion
```
hoping you can spot the obvious mistake. I have had this same model working using a NordVPN container recently, I have moved over to express though so kinda need to get it working that way.
