### ISSUE TITLE
How to use V2ray with ExpressVPN docker?

### ISSUE THREAD

**Issue by hellohawaii2** [polkaned/dockerfiles#47]
## what I want to do

V2ray is a proxy software that listens to a certain port on a server. I want to use it with ExpressVPN. So when the client accesses the port of V2ray, since v2ray is using VPN, the client can also get access to the ExpressVPN service. 

client -->  v2ray(docker with ExpressVPN)  --> server_from_ExpressVPN.

I was motivated by [this link](https://gist.github.com/zpoint/df2483c6beb97816e34ddbde3f62f5d8). I think **in this way, we can also break through the limit of the number of devices by ExpressVPN**. I install the v2ray (together with ExpressVPN) in a docker on a VPS.

## My problem

When my client uses the IPV4 address of VPS to access v2ray, it does not work. But by using the IPV6 address of VPS, my client succeed to access the ExpressVPN service.

In contrast, if I set v2ray in docker without ExpressVPN, both IPV4 and IPV6 addresses work.  It seems that when composed with ExpressVPN, the v2ray can not listen to the IPV4_addr:port while can listen to IPV6_addr:port.

## what I tried

I tried to use your image together with the official v2ray image.

My docker-compose.yml
```
services:
  expressvpn:
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE={MYCODE}
        #- SERVER={% LOCATION/ALIAS/COUNTRY %}
        #- PREFERRED_PROTOCOL={% protocol %}
        #- LIGHTWAY_CIPHER={% lightway-cipher %}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      - "43966:8388"
    # ports of other containers that use the vpn (to access them locally)
 
  v2ray:
    image: v2fly/v2fly-core
    volumes:
      - ./v2ray_config.json:/etc/v2fly/config.json  # refer to https://github.com/v2fly/docker 
    command:
      run -c /etc/v2fly/config.json
    network_mode: service:expressvpn
    depends_on:
      - expressvpn
```

And FYI, I create a v2ray_config.json in the same directory, using the simplest setting provided in [the v2ray website](https://www.v2ray.com/en/welcome/start.html)
```
{
  "inbounds": [{
    "port": 10086, // Port of the server. Must be the same as above.
    "protocol": "vmess",
    "settings": {
      "clients": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}
```
