### ISSUE TITLE
ExpressVPN:Latest For CasaOS users

### ISSUE THREAD

**Issue by Dethkiller15** [polkaned/dockerfiles#59]
Hello I had spent the most of 10 hours attempting to get this container to work in CasaOS. I hope this guide helps you.

### Setting Up The VPN itself

do the install as usual however, idk why but for whatever reason when installed unless you put in "sleep", "infinity" in command it goes into a loop. At least on my install.(I did try /bin/bash and nada)
![image](https://github.com/user-attachments/assets/38803307-e4d6-4b48-a2a6-6f704ee54461)

Ok that is it for the VPN container.

## Main Reason I am making this guide
Now due to the issues #57 and #55 you have 2 extra steps if you want to be secure with your connection and not have any leaks.
In any containers you want to use on the VPN you need to make it like so.

In "/DATA/AppData/ExpressVPN" make a new file named "resolv.conf"
Next in the ExpressVPN container go to the terminal and do "cat /etc/resolv.conf" and copy what you get into the "resolv.conf" file you made. or use the content below.(it shouldn't matter but if you cant ping anything in your containers then that is more than likely the reason)
```
# Generated by expressvpn
search expressvpn
nameserver 100.64.100.1
```

### Container Example

Then lets get to making a container that makes use of the VPN. As an example I will be using QBitTorrent
```
services:
  QBitTorrent:
    image: linuxserver/qbittorrent:4.6.5
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/qbittorrent/config
        target: /config
      - type: bind
        source: /DATA/AppData/qbittorrent/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/ExpressVPN/resolv.conf
        target: /etc/resolv.conf
    network_mode: container:ExpressVPN
```

Then you should be all set. Just make sure to open ports on the VPN container itself and not the containers making use of it. Oh and DONT set ```container_name: ""``` to ANYTHING as it breaks things.

### Sanity check.
Ok you are done and have everything set up. Good for you. Now you just gotta make sure it works before freaking out at why the hell you cant access google.com

In the terminals for each container do "curl ifconfig.io" or "wget -qO- ifconfig.io" and double check the IP it gives you isn't the same as when you run it on the host machine. If you cant get a response or get "bad address" error then you didn't pass resolv.conf correctly or the one in ExpressVPN and the one you are passing to your container are not a match.(double check in the VPN container itself as well if that command works as that could mean other issues.) you can also try ```nslookup google.com``` and look for if there is an issue there.

### Credit where it is due
https://www.youtube.com/watch?v=lSE5-9CpkNk
That video did help me not make some mistakes and do recommend a watch.
